/* VotaBrasil - Notificacoes PWA (50% / 70%) - v1 ASCII */
(function(){
  var KEY='vb_notifs', T_ALERTA=50, T_URGENTE=70;
  function store(){ try{ return JSON.parse(localStorage.getItem(KEY)||'[]'); }catch(e){ return []; } }
  function save(l){ try{ localStorage.setItem(KEY, JSON.stringify(l)); }catch(e){} }
  function beep(){ try{ var C=window.AudioContext||window.webkitAudioContext; var c=new C(); var o=c.createOscillator(); var g=c.createGain(); o.connect(g); g.connect(c.destination); o.frequency.value=880; g.gain.value=0.07; o.start(); setTimeout(function(){ o.stop(); c.close(); },180); }catch(e){} }
  function badge(){ var n=0,l=store(),i; for(i=0;i<l.length;i++){ if(!l[i].lida){ n++; } } var b=document.getElementById('vb-notif-badge'); if(b){ b.textContent=String(n); b.style.display=n?'flex':'none'; } }
  function pushN(n){ var l=store(); n.id=Date.now(); n.lida=false; l.unshift(n); if(l.length>50){ l=l.slice(0,50); } save(l); badge(); }
  function sysNotify(n){ if('Notification' in window && Notification.permission==='granted'){ try{ new Notification(n.titulo,{body:n.texto}); }catch(e){} } }
  function pctOf(c){ var d=c.getAttribute('data-revogado'); if(d){ return parseFloat(d); } var m=(c.textContent||'').match(/([0-9]{1,3})\s*%/); return m?parseFloat(m[1]):0; }
  function nomeOf(c){ var e=c.querySelector('h3,h4,strong'); return e?e.textContent.trim():'Politico'; }
  function idOf(c,n){ return (c.getAttribute('data-id')||n).replace(/[^A-Za-z0-9]+/g,'-'); }
  function modal70(nome,p){ if(document.getElementById('vb-modal70')){ return; } var d=document.createElement('div'); d.id='vb-modal70'; d.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.7);z-index:99998;display:flex;align-items:center;justify-content:center'; d.innerHTML='<div style="background:#1a1a2e;color:#fff;padding:24px;border-radius:12px;max-width:420px;border:2px solid #C0392B"><h2 style="color:#C0392B;margin:0 0 8px">URGENTE: '+nome+'</h2><p>Revogacao atingiu '+p+'% (regra de cassacao = 70%).</p><p>Gere o Relatorio de Cassacao (PDF) e protocole no TSE / Ministerio Publico.</p><button id="vb-m70-ok" style="background:#C0392B;color:#fff;border:0;padding:10px 16px;border-radius:8px;font-weight:700;cursor:pointer">Entendi</button></div>'; document.body.appendChild(d); document.getElementById('vb-m70-ok').onclick=function(){ d.remove(); }; }
  function scan(){ var cards=[].slice.call(document.querySelectorAll('.card,[data-revogado]')); cards.forEach(function(c){ var p=pctOf(c); if(!p){ return; } var nome=nomeOf(c); var id=idOf(c,nome); var l=store(); var has=function(t){ return l.some(function(x){ return x.ref===id&&x.tipo===t; }); }; if(p>=T_URGENTE&&!has('urgente70')){ var n={ref:id,tipo:'urgente70',titulo:'URGENTE: '+nome+' '+p+'%',texto:'Regra de cassacao (70%) atingida. Gere o relatorio PDF.'}; pushN(n); sysNotify(n); beep(); modal70(nome,p); } else if(p>=T_ALERTA&&!has('alerta50')&&!has('urgente70')){ var n2={ref:id,tipo:'alerta50',titulo:'ALERTA: '+nome+' '+p+'%',texto:'Metade dos eleitores ja revogou o voto.'}; pushN(n2); sysNotify(n2); } }); }
  function panel(){ var w=document.getElementById('vb-notif-panel'); if(w){ w.remove(); return; } var l=store(); var html='<div id="vb-notif-panel" style="position:fixed;right:12px;top:60px;z-index:99997;background:#111827;color:#fff;border:1px solid #334155;border-radius:10px;width:320px;max-height:60vh;overflow:auto;padding:12px"><h3 style="margin:0 0 8px">Notificacoes</h3>'; if(!l.length){ html+='<p>Sem notificacoes.</p>'; } l.forEach(function(x){ html+='<div style="border-left:3px solid '+(x.tipo==='urgente70'?'#C0392B':'#F1C40F')+';padding:6px;margin:6px 0;background:#0B132B"><b>'+x.titulo+'</b><br><small>'+x.texto+'</small></div>'; }); html+='<button id="vb-notif-limpar" style="margin-top:8px;background:#334155;color:#fff;border:0;padding:8px 12px;border-radius:6px;cursor:pointer">Marcar todas como lidas</button></div>'; document.body.insertAdjacentHTML('beforeend',html); document.getElementById('vb-notif-limpar').onclick=function(){ var l2=store(); l2.forEach(function(x){ x.lida=true; }); save(l2); badge(); document.getElementById('vb-notif-panel').remove(); }; }
  function ui(){ var b=document.createElement('button'); b.id='vb-notif-bell'; b.type='button'; b.textContent='\uD83D\uDD14'; b.style.cssText='position:fixed;right:12px;top:12px;z-index:99996;background:#1F2937;color:#fff;border:1px solid #334155;border-radius:20px;padding:6px 10px;cursor:pointer'; b.onclick=panel; var s=document.createElement('span'); s.id='vb-notif-badge'; s.style.cssText='display:none;position:absolute;top:-6px;right:-6px;background:#C0392B;color:#fff;border-radius:10px;padding:1px 6px;font-size:11px;font-weight:700'; b.appendChild(s); document.body.appendChild(b); if('Notification' in window && Notification.permission==='default'){ var bar=document.createElement('div'); bar.style.cssText='position:fixed;left:0;right:0;bottom:0;background:#0B132B;color:#fff;padding:10px 14px;z-index:99995;display:flex;gap:10px;align-items:center;border-top:1px solid #334155'; bar.innerHTML='<span>Ativar alertas de revogacao (50% / 70%)?</span><button id="vb-notif-ok" style="background:#009739;color:#fff;border:0;padding:8px 12px;border-radius:6px;font-weight:700;cursor:pointer">Ativar</button><button id="vb-notif-no" style="background:#334155;color:#fff;border:0;padding:8px 12px;border-radius:6px;cursor:pointer">Agora nao</button>'; document.body.appendChild(bar); document.getElementById('vb-notif-ok').onclick=function(){ Notification.requestPermission().then(function(){ bar.remove(); }); }; document.getElementById('vb-notif-no').onclick=function(){ bar.remove(); }; } badge(); }
  if(document.readyState==='loading'){ document.addEventListener('DOMContentLoaded',function(){ ui(); scan(); }); } else { ui(); scan(); }
  setInterval(scan,10000);
  window.VBNotif={store:store,scan:scan,limpar:function(){ save([]); badge(); }};
})();
